### ISSUE TITLE
setup.bat opens and immediately closes

### ISSUE THREAD

**Issue by AkiDaCumSlut** [p-cracker/DoLEditor#1]
I run the setup, and it opens a cmd prompt and closes immediately. I have Python 3.11.

**Comment by TWR-0** [comment]
I'll be sure to add some checks for common mishaps with the next update that will solve the issue with the game locking feats after enabling cheats.

**Comment by p-cracker** [comment]
I've updated the repo with new functionality and new setup scripts that should (hopefully) detect common issues with python installs and tell you about them instead of closing instantly.

**Comment by AkiDaCumSlut** [comment]
Latest update fixed it.
